---
title: "Fold Change"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(MicrobiomeBenchmarkData)
```


```{r}
tse <- getDataset("HMP_2012_16S_gingival_V35_subset", dryrun = FALSE)[[1]]
counts <-assay(tse) 
condition_vector <- colData(tse)[["hmp_body_subsite"]]
conditions <- c(condB = "subgingival_plaque", condA = "supragingival_plaque")



counts_tss <- apply(counts, 2, function(x) x / sum(x) * 1e6)
counts_tss <- counts_tss + 1

counts_clr <- apply(counts + 1, 2, function(x) log(x / exp(mean(log(x)))))
```


Calculate fold changes

Attempt one. There is pseudocount of 1 and the log is calculated using the
arithmetic mean

```{r}
taxa <- rownames(counts_tss)
output1 <- vector("double", length(taxa))
names(output1) <- taxa

for (i in seq_along(output1)) {
    
    mean_condB <- mean(counts_tss[taxa[i], condition_vector == conditions["condB"]])
    mean_condA <- mean(counts_tss[taxa[i], condition_vector == conditions["condA"]])
    
    if (mean_condA >= mean_condB) {
        output1[i] <- log2(mean_condA / mean_condB) 
    } else if (mean_condA < mean_condB) {
        output1[i] <- -log2(mean_condB / mean_condA)
    }
}

top_output1 <- list(top = head(sort(output1, TRUE)), bottom = head(sort(output1)))
top_output1
```

Let's do the same, but using the geometric mean

```{r}
taxa <- rownames(counts_clr)
output2 <- vector("double", length(taxa))
names(output2) <- taxa

for (i in seq_along(output2)) {
    
    mean_condB <- mean(counts_clr[taxa[i], condition_vector == conditions["condB"]])
    mean_condA <- mean(counts_clr[taxa[i], condition_vector == conditions["condA"]])
    
    output2[i] <- mean_condA - mean_condB
    
}

top_output2 <- list(top = head(sort(output2, TRUE)), bottom = head(sort(output2)))
top_output2
```


```{r}

taxa <- rownames(counts_tss)
output3 <- vector("double", length(taxa))
names(output3) <- taxa

for (i in seq_along(output3)) {
    
    mean_condB <- mean(counts_tss[taxa[i], condition_vector == conditions["condB"]])
    mean_condA <- mean(counts_tss[taxa[i], condition_vector == conditions["condA"]])
    
    output3[i] <- 
        gtools::foldchange2logratio(gtools::foldchange(mean_condA, mean_condB))
    
}

top_output3 <- list(top = head(sort(output3, TRUE)), bottom = head(sort(output3)))
top_output3
```

```{r}

intersect(head(names(sort(output1, T)), 30), head(names(sort(output2, T)), 30))


```



```{r}
output4 <- log2_fold_change(
    mat = counts_tss,
    condition_vector = condition_vector,
    condB = "subgingival_plaque"
)
top_output4 <- list(top = head(sort(output4, TRUE)), bottom = head(sort(output4)))
top_output4
```






