---
title: "Ravel_2011_16S_BV_MLRepo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyr)
library(purrr)
library(ggplot2)
```

Get URLs from https://knights-lab.github.io/MLRepo/docs/ravel_nugent_score.html

In this analysis, only the taxa_tables will be used instead of the OTUs


```{r}
sample_metadata_url <- 
    "https://knights-lab.github.io/MLRepo/datasets/ravel/task-nugent-category.txt"

taxa_table_gg97_url <- 
    "https://knights-lab.github.io/MLRepo/datasets/ravel/gg/taxatable.txt"

taxa_table_refseq_url <- 
    "https://knights-lab.github.io/MLRepo/datasets/ravel/refseq/taxatable.txt"

ranks <- c(
    "kingdom", "phylum", "class", "order", "family", "genus", "species"
)
```

Import sample metadata:

```{r}
sample_metadata <- readr::read_tsv(sample_metadata_url)
colnames(sample_metadata) <- sub("^#", "", colnames(sample_metadata))
colnames(sample_metadata)[2] <- "BV"
sample_metadata <- sample_metadata %>% 
    mutate(BV = ifelse(BV == "low", "Negative", "Positive"))

col_data <- sample_metadata %>% 
    column_to_rownames(var = "SampleID") %>% 
    as.data.frame()

```

Create a summarized experiment for the gg97 data

```{r}
taxa_table_gg97 <- readr::read_tsv(taxa_table_gg97_url)
colnames(taxa_table_gg97) <- sub("^#", "", colnames(taxa_table_gg97))

count_matrix_gg97 <- taxa_table_gg97 %>% 
    column_to_rownames(var ="OTU ID") %>%
    as.data.frame() %>% 
    as.matrix()
count_matrix_gg97 <- count_matrix_gg97[,sample_metadata$SampleID]
count_matrix_gg97 <- count_matrix_gg97[rowSums(count_matrix_gg97) > 0, ]

taxonomy_table_gg97 <- taxa_table_gg97 %>% 
    separate(col = `OTU ID`, into = ranks, sep = "; [a-z]__") %>% 
    mutate(kingdom = sub("^k__", "", kingdom)) %>% 
    select(all_of(ranks)) %>% 
    as.data.frame() %>% 
    magrittr::set_rownames(taxa_table_gg97$`OTU ID`)

taxonomy_table_gg97 <- taxonomy_table_gg97[rownames(count_matrix_gg97), ]

se_gg97 <- SummarizedExperiment(
    assays = S4Vectors::SimpleList(counts = count_matrix_gg97),
    colData = S4Vectors::DataFrame(col_data),
    rowData = S4Vectors::DataFrame(taxonomy_table_gg97)
)

assays(se_gg97)$relative_abundance <- 
    apply(assays(se_gg97)$counts, 2, function(x) x / sum(x) * 100)
```


```{r}
taxa_table_refseq <- readr::read_tsv(taxa_table_refseq_url)
colnames(taxa_table_refseq) <- sub("^#", "", colnames(taxa_table_refseq))

count_matrix_refseq <- taxa_table_refseq %>% 
    filter(!is.na(`OTU ID`)) %>% 
    column_to_rownames(var ="OTU ID") %>%
    as.data.frame() %>% 
    as.matrix()
count_matrix_refseq <- count_matrix_refseq[,sample_metadata$SampleID]
count_matrix_refseq <- count_matrix_refseq[rowSums(count_matrix_refseq) > 0, ]

taxonomy_table_refseq <- taxa_table_refseq %>% 
    filter(!is.na(`OTU ID`)) %>% 
    separate(
        col = `OTU ID`, into = ranks, sep = ";[a-z]__", remove = FALSE
    ) %>% 
    mutate(kingdom = sub("^k__", "", kingdom)) %>% 
    select(all_of(c("OTU ID", ranks))) %>% 
    as.data.frame()  
rownames(taxonomy_table_refseq) <- taxonomy_table_refseq$`OTU ID`
taxonomy_table_refseq$`OTU ID` <- NULL

taxonomy_table_refseq <- taxonomy_table_refseq[rownames(count_matrix_refseq), ]

se_refseq <- SummarizedExperiment(
    assays = S4Vectors::SimpleList(counts = count_matrix_refseq),
    colData = S4Vectors::DataFrame(col_data),
    rowData = S4Vectors::DataFrame(taxonomy_table_refseq)
)

assays(se_refseq)$relative_abundance <- 
    apply(assays(se_refseq)$counts, 2, function(x) x / sum(x) * 100)
```

```{r}
tidy_taxa_table_gg97 <- taxa_table_gg97_relative_abundance %>% 
    filter(grepl("Lactobacillus", `OTU ID`)) %>%
    mutate(`OTU ID` = sub("^.+(Lactobacillus).*$", "\\1", `OTU ID`)) %>% 
    group_by(`OTU ID`) %>% 
    summarise(across(-1, sum)) %>% 
    mutate(`OTU ID` = sub("^.+_", "", `OTU ID`)) %>% 
    pivot_longer(
        cols = 2:last_col(), names_to = "SampleID", values_to = "Abundance" 
    ) %>% 
    relocate(SampleID, OTU = `OTU ID`, Abundance) %>% 
    left_join(sample_metadata, by = "SampleID")
    
```


```{r}
tidy_taxa_table_gg97 %>% 
    filter(!is.na(nugent_score)) %>% 
    ggplot(aes(nugent_score, Abundance)) +
    geom_boxplot(aes(group = nugent_score, color = BV)) +
    geom_point(size = .5, shape = 1, position = "jitter")
```


