---
title: "Beghini_2019_16S_smoking"
output:
  html_document:
    toc: yes
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    message = FALSE,
    warning = FALSE
)
```

# Introduction

```{r setup}
library(benchdamic)
library(phyloseq)
library(mia)
library(MicrobiomeBenchmarkData)
library(MicrobiomeBenchmarkDataAnalyses)
library(dplyr)
```

Some useful variables:

```{r useful variables}
grp <- "grp"
conditions <- c("never_smoker", "cigarette")
```

# Import data

```{r import dataset}
dataset_name <- "Beghini_2019_16S_smoking"
tse <- getDataset(dataset_name, dryrun = FALSE)[[1]]
colData(tse)$grp <- factor(colData(tse)$smokingstatus, levels = conditions)
tse
```

```{r}
## Some names need to be fixed
rowData(tse)$Genus <- sub(" [0-9]+$", "", sub("^.+__", "", rowData(tse)$Genus))
tse_by_ranks <- splitByRanks(x = tse)
tse_genus <- tse_by_ranks$Genus
tse_genus <- tse_genus[!grepl("uncultured", rownames(tse_genus)),]
tse_genus
```

Import biological annotations:

```{r}
biosis_file <- system.file(
  "extdata/nychanes_biosis.tsv", 
  package = "MicrobiomeBenchmarkDataAnalyses"
)
biosis <- read.table(biosis_file, header = TRUE, sep = "\t")
biosis$biosis <- sub(" ", "_", biosis$biosis)
head(biosis)
```

# Analysys at the OTU level

## Prior knowledge

```{r}
priorInfo <- rowData(tse)["Genus"] %>% 
  as.data.frame() %>% 
  left_join(biosis, by = c("Genus"= "genera")) %>% 
  magrittr::set_rownames(rownames(tse)) %>% 
  mutate(
    Genus = ifelse(is.na(biosis), "Unknown", Genus),
    biosis = ifelse(is.na(biosis), "Unknown", biosis),
    newNames = paste0(rownames(tse), "|", Genus)
  )
head(priorInfo)
```

## Convert to phyloseq

```{r convert to phyloseq}
ps <- makePhyloseqFromTreeSummarizedExperiment(tse)
ps
```

Set reference:

```{r set reference}
## Using subgingival plaque as reference (contast[1])
sample_data(ps)[[grp]] <- factor(sample_data(ps)[[grp]])
sample_data(ps)[[grp]] <- relevel(x = sample_data(ps)[[grp]], ref = conditions[1])
```

## Run DA methods

```{r}
## Add normalization factors
ps <- quiet(runNormalizations(normalization_methods_list, ps))

## Calculate weights
zinbweights <- weights_ZINB(ps, design = "~ 1", K = 0)

## Run DA methods
DA_methods_list <- set_DA_methods_list(grp, conditions)
DA <- quiet(runDA(DA_methods_list, ps, weights = zinbweights))
str(DA, max.level = 1)
```

## Enrichment

Prepare directions for enrichment

```{r direction}
direction <- c(
    edgeR.TMM = "logFC", 
    DESeq2.poscounts = "log2FoldChange",
    limma.CSSmedian = "logFC",
    limma.TMM = "logFC",
    metgenomeSeq.CSSmedian = paste0(grp, conditions[2]),
    ALDEx2.none = "effect",
    corncob.none = "Estimate",
    MAST.none = "logFC",
    Seurat.none = "avg_log2FC",
    ZINQ = "log2FoldChange",
    ANCOMBC = "logFC",
    wilcox_test = "log2FoldChange",
    wilcox_test_clr = "log2FoldChange"
)
```

Run enrichment: 

```{r create enrichment}
enrichment <- createEnrichment(
    object = DA,
    priorKnowledge = priorInfo,
    enrichmentCol = "biosis",
    namesCol = "Genus",
    slot = "pValMat",
    colName = "adjP",
    type = "pvalue",
    direction = direction,
    threshold_pvalue = 0.1,
    threshold_logfc = 0,
    top = NULL,
    alternative = "greater",
    verbose = TRUE
)
```

Plot enrichment:

```{r, fig.height=7}
plotEnrichment(
    enrichment = enrichment, 
    enrichmentCol = "Type",
    levels_to_plot = c("Aerobic", "Anaerobic", "F_Anaerobic")
)

```

### TRUE and FALSE positives

Create table of positives

```{r create positives}
positives <- createPositives(
    object = DA, 
    priorKnowledge = priorInfo,
    enrichmentCol = "biosis",
    namesCol = "Genus",
    slot = "pValMat",
    colName = "rawP",
    type = "pvalue",
    direction = direction,
    threshold_pvalue = 1,
    threshold_logfc = 0,
    top = seq.int(from = 0, to = 50, by = 5),
    alternative = "greater",
    verbose = FALSE,
    TP = list(c("DOWN Abundant", "Anaerobic"), c("UP Abundant", "Aerobic")),
    FP = list(c("DOWN Abundant", "Aerobic"), c("UP Abundant", "Anaerobic"))
)

head(positives)
```

Plot positives

```{r}
ggp <- plotPositives(positives)
ggp
```







