---
title: "Bacterial vaginosis dataset - Ravel 2011"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This is an exploratory analysis of the bacterial vaginosis dataset published
in the article by [Ravel, et. al., 2011](https://knights-lab.github.io/MLRepo/docs/ravel.html).

There are a couple of options for downloading data about bacterial vaginosis
from the Microbiome ML-repo (
https://knights-lab.github.io/MLRepo/docs/ravel_nugent_category.html):
+ OTU table generated with greengenes 99 (gg97).
+ OTU table generated with RefSeq.

Packages:

```{r setup}
library(MicrobiomeBenchmarkDataAnalyses)
```






## Data from gg97

Sample metadata:

```{r}
sample_metadata_url <- "https://knights-lab.github.io/MLRepo/datasets/ravel/task-nugent-category.txt"
sample_metadata <- read.table(sample_metadata_url, sep = "\t", header = TRUE, comment.char = "")
colnames(sample_metadata) <- c("Sample", "Nugent")
head(sample_metadata)
```

OTU table: 

```{r}
otu_table_gg97_url <- "https://knights-lab.github.io/MLRepo/datasets/ravel/gg/otutable.txt"
otu_table_gg97 <- read.table(otu_table_gg97_url, sep = "\t", header = TRUE, comment.char = "")
rownames(otu_table_gg97) <- otu_table_gg97[[1]]
otu_table_gg97 <- as.matrix(otu_table_gg97[,-1])
otu_table_gg97[1:5, 1:5]
```

Taxa table:

```{r}
tax_table_gg97_url <- "https://knights-lab.github.io/MLRepo/datasets/ravel/gg/taxatable.txt"
tax_table_gg97 <- read.table(tax_table_gg97_url, sep = "\t", header = FALSE)
tax_table_gg97 <- tax_table_gg97[,-1]

```




