---
title: "HMP_2012_WMS_gingiva - Supragingival vs subgingival plaque"
output: 
    html_document:
        toc: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```


```{r setup}
library(MicrobiomeBenchmarkDataAnalyses)
library(MicrobiomeBenchmarkData)
library(mia)
library(phyloseq)
library(benchdamic)
library(dplyr)
library(purrr)
library(ggplot2)
library(gridExtra)
```

# Import data

```{r import data, message=FALSE, warning=FALSE}
dat_name <-'HMP_2012_WMS_gingival'
conditions_col <- 'body_subsite'
conditions <- c(condB = 'subgingival_plaque', condA = 'supragingival_plaque')

tse <- getBenchmarkData(dat_name, dryrun = FALSE)[[1]]
tse <- filterTaxa(tse)

colData(tse)[[conditions_col]] <- 
    factor(colData(tse)[[conditions_col]], levels = conditions)
tse
```

# Prior knowledge

```{r prior info}
row_data <- as.data.frame(rowData(tse))
prior_info <- row_data[, c('genus', 'taxon_annotation')]
prior_info$taxon_name <- rownames(prior_info)
prior_info$new_names <- paste0(prior_info$taxon_name, '|', prior_info$genus)
head(prior_info)
```

# Convert to phyloseq

```{r, message=FALSE, warning=FALSE}
ps <- makePhyloseqFromTreeSummarizedExperiment(tse)
phyloseq::sample_data(ps)$body_subsite <- 
    factor(phyloseq::sample_data(ps)$body_subsite)
ps
```

## Differential abundance analysis

Select methods for DA:

```{r, message=FALSE, warning=FALSE}
ps <- runNormalizations(set_norm_list(), ps, verbose = FALSE)
zw <- weights_ZINB(ps, design = conditions_col)
DA_methods <- set_DA_methods_list(conditions_col, conditions)

for (i in seq_along(DA_methods)) {
    if (grepl("Seurat", names(DA_methods)[i])) {
        names(DA_methods[[i]]$contrast) <- NULL
    } else {
        next
    }
}
# These methods throw an error, so they must be removed
# DA_methods <- DA_methods[!names(DA_methods) == 'DA_ALDEx2.1']
# DA_methods <- DA_methods[!names(DA_methods) == 'DA_corncob.1']
DA_methods <- DA_methods[!names(DA_methods) == 'DA_edgeR.1']
names(DA_methods)
```

```{r, warning=FALSE, message=TRU}
tim <- system.time({
    DA_output <- vector("list", length(DA_methods))
    for (i in seq_along(DA_output)) {
        message(
            "Running method ", i, ": ", names(DA_methods)[i], " - ", Sys.time()
        )
        DA_output[[i]] <- tryCatch(
            error = function(e) NULL,
            runDA(DA_methods[i], ps, weights = zw, verbose = FALSE) 
        )
    }
    DA_output <- purrr::list_flatten(DA_output, name_spec = "{inner}")
    DA_output <- purrr::discard(DA_output, is.null)
})
tim
```

# Enrichment

Get direction 

```{r}
direction <- get_direction_cols(DA_output, conditions_col, conditions)
```

## Enrichment (adjP <= 0.1)

```{r}
enrichment <- createEnrichment(
    object = DA_output,
    priorKnowledge = prior_info,
    enrichmentCol = "taxon_annotation",
    namesCol = "taxon_name",
    slot = "pValMat", colName = "adjP", type = "pvalue",
    direction = direction,
    threshold_pvalue = 0.1,
    threshold_logfc = 0,
    top = NULL, # No top feature selected
    alternative = "greater",
    verbose = FALSE 
)
```

## Plot enrichment

```{r, warning=FALSE, message=FALSE, fig.height=6, fig.width=10}
enrich_plot <- plot_enrichment(
    enrichment = enrichment, 
    enrichment_col = "taxon_annotation",
    levels_to_plot = c("aerobic", "anaerobic", "facultative_anaerobic"),
    conditions = conditions
)
enrich_plot2 <- plot_enrichment_2(
    enrich_plot,
    dir = c(up = 'Sup Plq', down = 'Sub Plq')
)
enrich_plot2
```

# Putative true positives - putative false positives

## Calculate TP - FP ratio (no threshold)

```{r positives}
positives <- createPositives(
    object = DA_output, 
    priorKnowledge = prior_info, 
    enrichmentCol = "taxon_annotation", namesCol = "taxon_name",
    slot = "pValMat", colName = "adjP", type = "pvalue",
    direction = direction,
    threshold_pvalue = 1,
    threshold_logfc = 0,
    top = seq.int(from = 0, to = 50, by = 5),
    alternative = "greater",
    verbose = FALSE,
    TP = list(c("DOWN Abundant", "anaerobic"), c("UP Abundant", "aerobic")),
    FP = list(c("DOWN Abundant", "aerobic"), c("UP Abundant", "anaerobic"))
) |> 
    left_join(get_meth_class(), by = 'method')
```

## Plot TP - FP 

```{r, fig.height = 10, fig.width=15}
positive_plots <- plot_positives(positives)
grid.arrange(grobs = positive_plots, ncol = 3)
```

# Session Info

```{r session info}
sessionInfo()
```
