---
title: "Analysis of the HMP_2012_16S_gingival_V35_subset dataset"
output: 
    html_document:
        toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE}
library(MicrobiomeBenchmarkData)
# library(MicrobiomeBenchmarkDataAnalyses)
library(phyloseq)
library(mia)
library(benchdamic)
library(purrr)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(randomcoloR)
```

# Import Data

```{r}
tse <- getDataset("HMP_2012_16S_gingival_V35_subset", dryrun = FALSE)[[1]]
conditions_col <- "hmp_body_subsite"
conditions <- c(condB = "subgingival_plaque", condA = "supragingival_plaque")
```

# Get prior knowledge (biological truth)

```{r}
row_data <- as.data.frame(rowData(tse))
taxaNames <- rownames(row_data)
newNames <- paste0(taxaNames, "|", row_data$GENUS) 
priorInfo <- data.frame(
    taxaNames = taxaNames,
    genus = row_data$GENUS,
    newNames = newNames,
    type = row_data$BIOSIS 
)
rownames(priorInfo) <- taxaNames
```

# Convert to phyloseq

```{r}
ps <- makePhyloseqFromTreeSummarizedExperiment(tse)

sample_data(ps)[[conditions_col]] <- 
    factor(sample_data(ps)[[conditions_col]], levels = conditions)
```

# Run DA methods

```{r warning=FALSE, message=FALSE}
DA_output <- run_DA(ps, conditions_col, conditions)

```


# Enrichment

## Get direction object


```{r}
direction <- get_direction_cols(DA_output, conditions_col, conditions)
```

## Create enrichment object

```{r}
enrichment <- createEnrichment(
    object = DA_output,
    priorKnowledge = priorInfo,
    enrichmentCol = "type",
    namesCol = "newNames",
    slot = "pValMat", colName = "rawP", type = "pvalue",
    direction = direction,
    threshold_pvalue = 0.05,
    threshold_logfc = 0,
    top = NULL,
    alternative = "greater",
    verbose = FALSE 
)
```


## Plot enrichment

```{r, warning=FALSE, message=FALSE, fig.height=6, fig.width=10}
enrich_plot <- plot_enrichment(
    enrichment = enrichment, 
    enrichment_col = "type",
    levels_to_plot = c("Aerobic", "Anaerobic", "F Anaerobic"),
    conditions = conditions
)
enrich_plot

```

# Putative true positives - putative false positives

## Create positives object

```{r}
positives <- createPositives(
    object = DA_output, 
    priorKnowledge = priorInfo, enrichmentCol = "type", namesCol = "newNames",
    slot = "pValMat", colName = "rawP", type = "pvalue",
    direction = direction,
    threshold_pvalue = 0.05,
    threshold_logfc = 0,
    top = seq.int(from = 0, to = 50, by = 5),
    alternative = "greater",
    verbose = FALSE,
    TP = list(c("DOWN Abundant", "Anaerobic"), c("UP Abundant", "Aerobic")),
    FP = list(c("DOWN Abundant", "Aerobic"), c("UP Abundant", "Anaerobic"))
)
```


## Plot enrichment








### LEFSE

```{r}
output_lefse_none <- DA_lefse(
    object = ps, grp = grp, ref = conditions[["condB"]],
    kruskal.threshold = 1,
    wilcox.threshold = 1,
    lda.threshold = 0,
    norm = 'none'
)

output_lefse_clr <- DA_lefse(
    object = ps, grp = grp, ref = conditions[["condB"]],
    kruskal.threshold = 1,
    wilcox.threshold = 1,
    lda.threshold = 0,
    norm = "CLR"
)
```




```{r}
meth_class <- method_classification()
positives2 <- left_join(meth_class, positives, by = 'method') %>% 
    relocate(method_class)
# positives2 <- positives2 %>% 
#     mutate(
#         base_method = sub("\\..*", "", method)
#     )
```




```{r}

max_top <- max(positives2$TP - positives2$FP)
min_top <- min(positives2$TP - positives2$FP)

x <- split(positives2, positives2$method_class)
df <- x[[2]]
df <- df %>% 
    mutate(
        across(.cols = where(is.character), .fns = ~ forcats::fct_inorder(.x)),
        shape = forcats::fct_inorder(as.character(shape))
        )
        

(
p1 <- df %>%
        ggplot2::ggplot(ggplot2::aes(x = top, y = TP - FP)) +
        ggplot2::geom_path(
            ggplot2::aes(color = color, group = method, linetype = norm)
        ) +
        ggplot2::geom_point(
            ggplot2::aes(color = color, shape = norm),
            size = 3
        ) +
        ggplot2::facet_wrap(.~ method_class) +
        ggplot2::scale_y_continuous(
            limits = c(min_top - 3, max_top + 3)
        ) +
        ggplot2::scale_color_manual(
            values = levels(df$color), labels = levels(df$base_method)
            
        ) +
        ggplot2::scale_shape_manual(
            values = as.integer(levels(df$shape)), labels = levels(df$norm)
        ) +
        ggplot2::scale_linetype_manual(
            values = as.integer(levels(df$shape)), labels = levels(df$norm)
        ) +
        ggplot2::labs(
            x = 'Top', y = 'TP - FP'
        ) +
        ggplot2::theme_bw() +
        ggplot2::theme(
            legend.position = c(0.01, 0.97),
            legend.justification = c("left", "top"),
            legend.title = ggplot2::element_blank(),
            legend.box.background = element_rect(color = "white", fill = 'white'
            )
        ) 
) 

```




```{r, fig.height = 12, fig.width=10}
plots <- plot_positives(positives2)

# first_plot <- plots[1] 
# other_plots <- plots[2:length(plots)]
# other_plots <- lapply(other_plots, function(x) {
#     x <- x +
#         theme(
#             axis.text.y = element_blank(),
#             axis.title.y = element_blank(),
#             axis.ticks.y = element_blank()
#         )
#     x
# })
# 
# plots2 <- c(first_plot, other_plots)

grid.arrange(grobs = plots, ncol = 2)


```


