---
title: "Sammler_2016_16S_spikein - Spike-in bacteria"
subtitle: "Comparison of coefficient of variation"
output:
    html_document:
        toc: yes
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE}
library(MicrobiomeBenchmarkDataAnalyses)
library(MicrobiomeBenchmarkData)
library(dplyr)
library(tibble)
library(tidyr)
library(biobroom)
library(ggplot2)
```


# Data

```{r, message=FALSE, warning=FALSE}
tse <- getBenchmarkData('Stammler_2016_16S_spikein', dryrun = FALSE)[[1]]
```

## Recalibrate with spike-in Salinibacter ruber

```{r}
spk_bac <- c(
    `S. ruber` = 'AF323500XXXX', 
    `R. radiobacter` = 'AB247615XXXX',
    `A. acidiphilus` = 'AB076660XXXX'
)

counts <- assay(tse, 'counts')
s_ruber <- counts[spk_bac['S. ruber'], ]

size_factor <- s_ruber/mean(s_ruber)
SCML_data <- counts 
for(i in seq(ncol(SCML_data))){
    SCML_data[,i] <- round(SCML_data[,i] / size_factor[i])
}

assay(tse, 'counts_recal') <- SCML_data
```

## Tranform with TSS (relative abundance) and CLR

```{r}
tss_fun <- function(x) (x + 1) / sum((x + 1))
## Coefficient of variation should not be calculated on log-tranformed data
## Therefore, calculate coefficient of variation on the data divided by
## the geomeric mean
clr_fun <- function(x) (x + 1) / exp(mean(log((x + 1))))
# clr_fun <- function(x) log((x + 1) / exp(mean(log((x + 1)))))
# clr_fun <- function(x) compositions::clr(x + 1)

## TSS (relative abundance)
assay(tse, "TSS") <- apply(assay(tse, 'counts'), 2,  tss_fun)

## CLR
assay(tse, "CLR") <- apply(assay(tse, 'counts'), 2, clr_fun) 
```

# Extract data of sipike-in bacteria

```{r}
spk_bac_tse <- tse[spk_bac,]
rownames(spk_bac_tse) <- names(spk_bac)
spk_bac_tse
```

# Get tidy data

```{r, message=FALSE, warning=FALSE}
## sample metadata
# col_data <- tse %>% 
#     colData() %>% 
#     as.data.frame() %>% 
#     rownames_to_column(var = "sample") %>% 
#     as_tibble() %>% 
#     select(sample, subject_id, study_condition)

## data for relative abundance
output <- vector("list", length(assays(spk_bac_tse)))
for (i in seq_along(output)) {
    data_name <- names(assays(spk_bac_tse))[i]
    names(output)[i] <- data_name
    output[[i]] <- tidy.RangedSummarizedExperiment(
        spk_bac_tse, assay = data_name
    ) %>% 
        magrittr::set_colnames(c('taxon', 'sample', data_name))
}
data <- purrr::reduce(output, left_join)
DT::datatable(data, filter = 'top')
```

# Calculate coefficient of variation

## Define formula for calculating coefficient of variation

```{r}
get_cv <- function(x) {
    cv <- function(x, n) { sd(x[n]) / mean(x[n]) * 100 } 
    boot::boot(x, cv, R = 1000) |>
        broom::tidy() |>
        dplyr::rename(cv = statistic)
} 
```

```{r}
cv_res <- data %>% 
    group_by(taxon) %>% 
    summarize(across(.cols = counts:last_col(), .fns = get_cv)) %>% 
    pivot_longer(
        cols = 2:last_col(), names_to = 'norm', values_to = 'cv_res' 
    ) %>% 
    unnest(cols = 'cv_res')
   
DT::datatable(cv_res, filter = 'top')     
```

Table in wider format:

```{r}
cv_res |> 
    rename(
        Species = taxon, `Normalization method` = norm,
        CV = cv, SE = std.error
    ) |> 
    filter(`Normalization method` %in% c("CLR", "TSS")) |> 
    select(-bias) |> 
    mutate(
        CV = round(CV, 1), SE = round(SE, 1)
    ) |> 
    mutate(
        `Normalization method` = ifelse(`Normalization method` == "TSS", "Relative abundance", `Normalization method`)
    ) |> 
    DT::datatable(
        extensions = 'Buttons',,
        filter = "top",
        options = list(
        dom = 'Bfrtip',
        buttons = list(
            list(
                extend = 'copy',
                text = 'Copy '
                )
            )
        )
    )


```

# Compare coefficient of variation

```{r, fig.width=8, fig.height=4}
cv_res %>% 
    filter(norm != 'counts') %>%
    mutate(norm = ifelse(norm == 'TSS', 'Relative abundance', norm)) %>%
    mutate(norm = ifelse(norm == 'counts_recal', 'Recalibrated counts', norm)) %>%
    mutate(
        norm = factor(norm, levels = c(
            'counts', 'Recalibrated counts', 'Relative abundance',  'CLR'
            )
        )
    ) %>%
    mutate(taxon = forcats::fct_relevel(taxon, 'S. ruber')) %>% 
    ggplot(aes(reorder(norm, cv), cv)) +
    geom_point(aes(color = norm), size = 2) + 
    geom_errorbar(
        aes(ymin = cv - std.error, ymax = cv + std.error, color = norm),
        width = 0.4, size = 0.5
    ) +
    scale_color_brewer(type = 'qual', palette = 'Set2') +
    facet_wrap(~taxon) + 
    labs(
        y = 'Coefficient of variation across all samples',
        x = 'Data transformation'
    ) + 
    theme_bw() + 
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.major.x = element_blank(),
        strip.text = element_text(face = 'italic'),
        # legend.title = element_blank()
        legend.position = 'none'
    )
```

# Session info
```{r}
sessionInfo()
```
