---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Try different parameters for the arguments

Using adjusted pvalue with threshold of 0.1

```{r}
enrichment_1 <- createEnrichment(
    object = DA_results,
    priorKnowledge = priorInfo,
    enrichmentCol = "type",
    namesCol = "newNames",
    slot = "pValMat", colName = "adjP", type = "pvalue",
    direction = direction,
    threshold_pvalue = 0.1,
    threshold_logfc = 0,
    top = NULL,
    alternative = "greater",
    verbose = FALSE 
)
```



```{r, warning=FALSE, message=FALSE}
enrich_plot <- plot_enrichment(
    enrichment = enrichment_1, 
    enrichment_col = "type",
    levels_to_plot = c("Aerobic", "Anaerobic", "F Anaerobic"),
    conditions = conditions
)
enrich_plot

```



Using raw pvalue of 0.05


```{r}
enrichment_2 <- createEnrichment(
    object = DA_results,
    priorKnowledge = priorInfo,
    enrichmentCol = "type",
    namesCol = "newNames",
    slot = "pValMat", colName = "rawP", type = "pvalue",
    direction = direction,
    threshold_pvalue = 0.05,
    threshold_logfc = 0,
    top = NULL,
    alternative = "greater",
    verbose = FALSE 
)
```





```{r, warning=FALSE, message=FALSE}
enrich_plot <- plot_enrichment(
    enrichment = enrichment_2, 
    enrichment_col = "type",
    levels_to_plot = c("Aerobic", "Anaerobic", "F Anaerobic"),
    conditions = conditions
)
enrich_plot

```





